# **Exercise: Basics of Python and Numpy**

1. Import numpy and print the numpy version. (Hint: use ```__version___``` attribute to check package version.)

In [57]:
# I created a special venv for the labs
import numpy as np
print(np.__version__)

2.3.2


2. Create a 4 x 5 matrix filled with random values. Name it as ```x```.

In [58]:
x = np.random.random((4, 5))
x

array([[0.15235863, 0.84687229, 0.23105265, 0.64038762, 0.05020247],
       [0.91230533, 0.70646618, 0.20806563, 0.65092095, 0.64541598],
       [0.63350857, 0.21606277, 0.30172054, 0.42814949, 0.91108323],
       [0.37386737, 0.22754397, 0.34047729, 0.57528695, 0.28890705]])

3. Create a 3 x 3 matrix filled with [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Name it as ```y```.

In [60]:
y = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
np.shape(y)

(3, 3)

4. Swap the first two rows of ```x```.

In [61]:
x[[1, 0]] = x[[0, 1]]
x

array([[0.91230533, 0.70646618, 0.20806563, 0.65092095, 0.64541598],
       [0.15235863, 0.84687229, 0.23105265, 0.64038762, 0.05020247],
       [0.63350857, 0.21606277, 0.30172054, 0.42814949, 0.91108323],
       [0.37386737, 0.22754397, 0.34047729, 0.57528695, 0.28890705]])

5. Create a random numpy array with shape (100, 2) and name it ```z```. Each row indicates the coordinates of a point. Compute point by point distances.

In [62]:
# I couldn't find and other way avoiding the loop!

nb_rows = 100
nb_columns = 2
z = np.random.random((nb_rows, nb_columns))
distances = np.zeros(nb_rows-1)

for i, values in enumerate(z): 
    if i == 99:
        pass
    else:
        d = np.sqrt(np.exp2(z[i+1][0] - z[i][0]) + 
                    np.exp2(z[i+1][1] - z[i][1])
                   )
        distances[i] = d
        
print(distances)

[1.4744739  1.48409241 1.41136316 1.39592099 1.61676203 1.22426791
 1.49555947 1.53291903 1.33775506 1.60466003 1.32106626 1.45992258
 1.22230938 1.60730236 1.37671261 1.50531102 1.53178835 1.29300024
 1.59880549 1.27100579 1.30400026 1.4924418  1.41074666 1.59702048
 1.22589733 1.33350863 1.51150259 1.397977   1.59052934 1.40532331
 1.60333828 1.29150304 1.38718704 1.54467984 1.37914914 1.44425149
 1.42862769 1.41310074 1.64796146 1.28228792 1.46858302 1.55955813
 1.29807617 1.47752397 1.3420335  1.48380326 1.53174979 1.14067358
 1.78252191 1.35498523 1.37496789 1.46329346 1.16875038 1.84104454
 1.10527795 1.70126705 1.28957316 1.5646902  1.18936782 1.40014255
 1.74234907 1.44336418 1.23825081 1.68312802 1.34739074 1.41354501
 1.32901192 1.40322614 1.53952853 1.5414046  1.5338425  1.21324327
 1.52524034 1.3211762  1.29393058 1.69508501 1.4486815  1.52003276
 1.31547028 1.36972848 1.52167863 1.26350659 1.77420225 1.05516968
 1.69250958 1.4242203  1.3431667  1.50658749 1.46575298 1.2912

6. Subtract the mean of each row of ```y```.

In [63]:
mean_rows = y.mean(axis=1, keepdims=True)
y = y - mean_rows
y

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

7. Add a vector [1, 0, 1] to each row of ```y``` using broadcasting and name the resulting numpy array as ```yy```.

In [64]:
v = np.array([[1, 0, 1]])
yy = y + v
yy

array([[0., 0., 2.],
       [0., 0., 2.],
       [0., 0., 2.]])

8. For each row in ```yy```, extract the value that are not equal to the other two values. Organize these values as a numpy array.

In [66]:
# I use ChatGPT for the "unique" because I didn't remember how to create a kind of boolean to select the unique values
a = []
for row in yy:
    values, counts = np.unique(row, return_counts=True)
    unique_value = values[counts == 1]
    a.append(unique_value)
a = np.array(a)
a

array([[2.],
       [2.],
       [2.]])